package com.example.spring.wechat.taxi.repository;

import com.example.spring.wechat.taxi.model.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import java.sql.Timestamp;
import java.util.List;

@Repository
public class RideRepository {
    private final JdbcTemplate jdbc;
    public RideRepository(JdbcTemplate jdbc) { this.jdbc = jdbc; }
    public void saveQuote(RideQuote q, String raw) {
        jdbc.update("INSERT INTO ride_quotes(quote_id,session_key,origin_name,origin_location,destination_name,destination_location,estimate_trace_id,raw_json,expires_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE raw_json=VALUES(raw_json),expires_at=VALUES(expires_at)", q.quoteId(),q.sessionKey(),q.originName(),q.originLocation(),q.destinationName(),q.destinationLocation(),q.estimateTraceId(),raw,Timestamp.from(q.expiresAt()),Timestamp.from(java.time.Instant.now()));
        jdbc.update("DELETE FROM ride_quote_options WHERE quote_id=?",q.quoteId());
        for(int i=0;i<q.options().size();i++){RideQuoteOption o=q.options().get(i);jdbc.update("INSERT INTO ride_quote_options(quote_id,option_index,product_category,option_name,min_price,max_price,duration_seconds,raw_json) VALUES(?,?,?,?,?,?,?,?)",q.quoteId(),i+1,o.productCategory(),o.name(),o.minPrice(),o.maxPrice(),o.durationSeconds(),o.rawJson());}
    }
    public RideQuote findQuote(String id){List<RideQuote> b=jdbc.query("SELECT * FROM ride_quotes WHERE quote_id=?",(r,n)->new RideQuote(id,r.getString("session_key"),r.getString("origin_name"),r.getString("origin_location"),r.getString("destination_name"),r.getString("destination_location"),r.getString("estimate_trace_id"),List.of(),r.getTimestamp("expires_at").toInstant()),id);if(b.isEmpty())return null;RideQuote q=b.get(0);List<RideQuoteOption> os=jdbc.query("SELECT * FROM ride_quote_options WHERE quote_id=? ORDER BY option_index",(r,n)->new RideQuoteOption(String.valueOf(r.getInt("option_index")),r.getString("product_category"),r.getString("option_name"),r.getBigDecimal("min_price"),r.getBigDecimal("max_price"),(Integer)r.getObject("duration_seconds"),r.getString("raw_json")),id);return new RideQuote(q.quoteId(),q.sessionKey(),q.originName(),q.originLocation(),q.destinationName(),q.destinationLocation(),q.estimateTraceId(),os,q.expiresAt());}
    public RideQuote findLatestQuote(String sessionKey){List<String> ids=jdbc.query("SELECT quote_id FROM ride_quotes WHERE session_key=? ORDER BY created_at DESC LIMIT 1",(r,n)->r.getString(1),sessionKey);return ids.isEmpty()?null:findQuote(ids.get(0));}
    public void saveOrder(RideOrder o){jdbc.update("INSERT INTO ride_orders(order_id,session_key,quote_id,product_category,status,driver_name,driver_phone,vehicle_plate,eta_seconds,final_fare,raw_json,updated_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status),driver_name=VALUES(driver_name),driver_phone=VALUES(driver_phone),vehicle_plate=VALUES(vehicle_plate),eta_seconds=VALUES(eta_seconds),final_fare=VALUES(final_fare),raw_json=VALUES(raw_json),updated_at=VALUES(updated_at)",o.orderId(),o.sessionKey(),o.quoteId(),o.productCategory(),o.status().name(),o.driverName(),o.driverPhone(),o.vehiclePlate(),o.etaSeconds(),o.finalFare(),o.rawJson(),Timestamp.from(o.updatedAt()),Timestamp.from(o.updatedAt()));}
    private RideOrder map(java.sql.ResultSet r)throws java.sql.SQLException{return new RideOrder(r.getString("order_id"),r.getString("session_key"),r.getString("quote_id"),r.getString("product_category"),RideOrderStatus.valueOf(r.getString("status")),r.getString("driver_name"),r.getString("driver_phone"),r.getString("vehicle_plate"),(Integer)r.getObject("eta_seconds"),r.getBigDecimal("final_fare"),r.getString("raw_json"),r.getTimestamp("updated_at").toInstant());}
    public RideOrder findOrder(String id){List<RideOrder> x=jdbc.query("SELECT * FROM ride_orders WHERE order_id=?",(r,n)->map(r),id);return x.isEmpty()?null:x.get(0);}
    public List<RideOrder> activeOrders(){return jdbc.query("SELECT * FROM ride_orders WHERE status NOT IN ('COMPLETED','PAID','CANCELLED','PAYMENT_FAILED')",(r,n)->map(r));}
    public void saveLocationConfirmation(RideLocationConfirmation c){jdbc.update("INSERT INTO ride_location_confirmations(confirmation_id,session_key,city,origin_name,origin_address,origin_location,destination_name,destination_address,destination_location,expires_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,NOW(3))",c.confirmationId(),c.sessionKey(),c.city(),c.originName(),c.originAddress(),c.originLocation(),c.destinationName(),c.destinationAddress(),c.destinationLocation(),Timestamp.from(c.expiresAt()));}
    public RideLocationConfirmation findLocationConfirmation(String id){List<RideLocationConfirmation>x=jdbc.query("SELECT * FROM ride_location_confirmations WHERE confirmation_id=?",(r,n)->new RideLocationConfirmation(r.getString("confirmation_id"),r.getString("session_key"),r.getString("city"),r.getString("origin_name"),r.getString("origin_address"),r.getString("origin_location"),r.getString("destination_name"),r.getString("destination_address"),r.getString("destination_location"),r.getTimestamp("expires_at").toInstant()),id);return x.isEmpty()?null:x.get(0);}
    public RideLocationConfirmation findLatestLocationConfirmation(String sessionKey){List<String> ids=jdbc.query("SELECT confirmation_id FROM ride_location_confirmations WHERE session_key=? ORDER BY created_at DESC LIMIT 1",(r,n)->r.getString(1),sessionKey);return ids.isEmpty()?null:findLocationConfirmation(ids.get(0));}
}
