CREATE TABLE IF NOT EXISTS wechat_images (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    wechat_user_id VARCHAR(191) NOT NULL,
    conversation_id BIGINT NULL,
    message_id VARCHAR(191) NULL,
    source_type VARCHAR(32) NOT NULL,
    source_reference VARCHAR(255) NULL,
    image_index INT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(191) NULL,
    sha256 VARCHAR(128) NULL,
    md5 VARCHAR(128) NULL,
    size_bytes BIGINT NOT NULL DEFAULT 0,
    local_path VARCHAR(1024) NULL,
    image_url VARCHAR(1024) NULL,
    prompt MEDIUMTEXT NULL,
    description MEDIUMTEXT NULL,
    status VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    used_at DATETIME(3) NULL,
    KEY idx_wechat_images_user_created (wechat_user_id, created_at),
    KEY idx_wechat_images_user_status (wechat_user_id, status),
    KEY idx_wechat_images_conversation_index (conversation_id, image_index),
    KEY idx_wechat_images_sha256 (sha256)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
