spring.application.name=wechat-weather-bot

# ===== ??API?? =====
# ????API????????????
weather.key=SvrNBNL1PWbX-I9Ot

# ===== ??????? =====
# ??????????
wechat.login.timeout=180000
# ????????
wechat.heartbeat.interval=30000
# ????????
wechat.auto.reconnect=true